/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatePostInput = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'isAnonymous' : IDL.Bool,
  'caption' : IDL.Text,
});
export const PostId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Post = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'imageBlob' : ExternalBlob,
  'createdAt' : Timestamp,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Opt(UserId),
  'updatedAt' : Timestamp,
  'caption' : IDL.Text,
  'savedCount' : IDL.Nat,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Post),
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'isAnonymousByDefault' : IDL.Bool,
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'isAnonymousByDefault' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([CreatePostInput], [Post], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'explorePosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getSavedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'getUserFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getUserFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'homeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
  'savePost' : IDL.Func([PostId], [], []),
  'searchPosts' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Page], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'unsavePost' : IDL.Func([PostId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatePostInput = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'isAnonymous' : IDL.Bool,
    'caption' : IDL.Text,
  });
  const PostId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Post = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'imageBlob' : ExternalBlob,
    'createdAt' : Timestamp,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Opt(UserId),
    'updatedAt' : Timestamp,
    'caption' : IDL.Text,
    'savedCount' : IDL.Nat,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Post),
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'isAnonymousByDefault' : IDL.Bool,
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'isAnonymousByDefault' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([CreatePostInput], [Post], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'explorePosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getSavedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'getUserFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getUserFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'homeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
    'savePost' : IDL.Func([PostId], [], []),
    'searchPosts' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Page], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'unsavePost' : IDL.Func([PostId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };