/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DrawingId = IDL.Nat;
export const UserId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const Drawing = IDL.Record({
  'id' : DrawingId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'imageBlob' : ExternalBlob,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : UserId,
  'updatedAt' : Timestamp,
  'savedCount' : IDL.Nat,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Drawing),
});
export const CreateDrawingInput = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
});
export const UpdateDrawingInput = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDrawing' : IDL.Func([DrawingId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDrawing' : IDL.Func([DrawingId], [IDL.Opt(Drawing)], ['query']),
  'getLikedBy' : IDL.Func([DrawingId], [IDL.Vec(UserId)], ['query']),
  'getSavedDrawings' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'getSuggestedDrawings' : IDL.Func([IDL.Nat], [IDL.Vec(Drawing)], ['query']),
  'getTrendingDrawings' : IDL.Func([IDL.Nat], [IDL.Vec(Drawing)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likeDrawing' : IDL.Func([DrawingId], [], []),
  'listDrawings' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'listDrawingsByTag' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'postDrawing' : IDL.Func([CreateDrawingInput], [Drawing], []),
  'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
  'saveDrawing' : IDL.Func([DrawingId], [], []),
  'searchDrawings' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Page], ['query']),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unlikeDrawing' : IDL.Func([DrawingId], [], []),
  'unsaveDrawing' : IDL.Func([DrawingId], [], []),
  'updateDrawing' : IDL.Func([DrawingId, UpdateDrawingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DrawingId = IDL.Nat;
  const UserId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const Drawing = IDL.Record({
    'id' : DrawingId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'imageBlob' : ExternalBlob,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : UserId,
    'updatedAt' : Timestamp,
    'savedCount' : IDL.Nat,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Drawing),
  });
  const CreateDrawingInput = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
  });
  const UpdateDrawingInput = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDrawing' : IDL.Func([DrawingId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDrawing' : IDL.Func([DrawingId], [IDL.Opt(Drawing)], ['query']),
    'getLikedBy' : IDL.Func([DrawingId], [IDL.Vec(UserId)], ['query']),
    'getSavedDrawings' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'getSuggestedDrawings' : IDL.Func([IDL.Nat], [IDL.Vec(Drawing)], ['query']),
    'getTrendingDrawings' : IDL.Func([IDL.Nat], [IDL.Vec(Drawing)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likeDrawing' : IDL.Func([DrawingId], [], []),
    'listDrawings' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'listDrawingsByTag' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'postDrawing' : IDL.Func([CreateDrawingInput], [Drawing], []),
    'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
    'saveDrawing' : IDL.Func([DrawingId], [], []),
    'searchDrawings' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unlikeDrawing' : IDL.Func([DrawingId], [], []),
    'unsaveDrawing' : IDL.Func([DrawingId], [], []),
    'updateDrawing' : IDL.Func([DrawingId, UpdateDrawingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };