/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateDrawingInput {
  'title' : string,
  'imageBlob' : ExternalBlob,
  'tags' : Array<string>,
  'description' : string,
}
export interface Drawing {
  'id' : DrawingId,
  'title' : string,
  'likeCount' : bigint,
  'imageBlob' : ExternalBlob,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'author' : UserId,
  'updatedAt' : Timestamp,
  'savedCount' : bigint,
}
export type DrawingId = bigint;
export type ExternalBlob = Uint8Array;
export interface Page {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Drawing>,
}
export type Timestamp = bigint;
export interface UpdateDrawingInput {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
}
export interface UpdateProfileInput {
  'bio' : string,
  'username' : string,
  'avatarBlob' : [] | [ExternalBlob],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDrawing' : ActorMethod<[DrawingId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDrawing' : ActorMethod<[DrawingId], [] | [Drawing]>,
  'getLikedBy' : ActorMethod<[DrawingId], Array<UserId>>,
  'getSavedDrawings' : ActorMethod<[bigint, bigint], Page>,
  'getSuggestedDrawings' : ActorMethod<[bigint], Array<Drawing>>,
  'getTrendingDrawings' : ActorMethod<[bigint], Array<Drawing>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowingUser' : ActorMethod<[UserId], boolean>,
  'likeDrawing' : ActorMethod<[DrawingId], undefined>,
  'listDrawings' : ActorMethod<[bigint, bigint], Page>,
  'listDrawingsByTag' : ActorMethod<[string, bigint, bigint], Page>,
  'postDrawing' : ActorMethod<[CreateDrawingInput], Drawing>,
  'saveCallerUserProfile' : ActorMethod<[UpdateProfileInput], undefined>,
  'saveDrawing' : ActorMethod<[DrawingId], undefined>,
  'searchDrawings' : ActorMethod<[string, bigint, bigint], Page>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unlikeDrawing' : ActorMethod<[DrawingId], undefined>,
  'unsaveDrawing' : ActorMethod<[DrawingId], undefined>,
  'updateDrawing' : ActorMethod<[DrawingId, UpdateDrawingInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];