/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePostInput {
  'title' : string,
  'imageBlob' : ExternalBlob,
  'isAnonymous' : boolean,
  'caption' : string,
}
export type ExternalBlob = Uint8Array;
export interface Page {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Post>,
}
export interface Post {
  'id' : PostId,
  'title' : string,
  'likeCount' : bigint,
  'imageBlob' : ExternalBlob,
  'createdAt' : Timestamp,
  'isAnonymous' : boolean,
  'author' : [] | [UserId],
  'updatedAt' : Timestamp,
  'caption' : string,
  'savedCount' : bigint,
}
export type PostId = bigint;
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'bio' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'isAnonymousByDefault' : boolean,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'postCount' : bigint,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'isAnonymousByDefault' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[CreatePostInput], Post>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'explorePosts' : ActorMethod<[bigint, bigint], Page>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostLikeCount' : ActorMethod<[PostId], bigint>,
  'getSavedPosts' : ActorMethod<[bigint, bigint], Page>,
  'getUserFollowers' : ActorMethod<[UserId], Array<UserProfile>>,
  'getUserFollowing' : ActorMethod<[UserId], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'homeFeed' : ActorMethod<[bigint, bigint], Page>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowingUser' : ActorMethod<[UserId], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UpdateProfileInput], undefined>,
  'savePost' : ActorMethod<[PostId], undefined>,
  'searchPosts' : ActorMethod<[string, bigint, bigint], Page>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'unsavePost' : ActorMethod<[PostId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];