/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UpdateDrawingInput {
    title: string;
    tags: Array<string>;
    description: string;
}
export type DrawingId = bigint;
export interface CreateDrawingInput {
    title: string;
    imageBlob: ExternalBlob;
    tags: Array<string>;
    description: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface Drawing {
    id: DrawingId;
    title: string;
    likeCount: bigint;
    imageBlob: ExternalBlob;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    author: UserId;
    updatedAt: Timestamp;
    savedCount: bigint;
}
export interface UpdateProfileInput {
    bio: string;
    username: string;
    avatarBlob?: ExternalBlob;
}
export interface Page {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Drawing>;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    username: string;
    avatarBlob?: ExternalBlob;
    createdAt: Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDrawing(id: DrawingId): Promise<void>;
    followUser(target: UserId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDrawing(id: DrawingId): Promise<Drawing | null>;
    getLikedBy(id: DrawingId): Promise<Array<UserId>>;
    getSavedDrawings(offset: bigint, limit: bigint): Promise<Page>;
    getSuggestedDrawings(limit: bigint): Promise<Array<Drawing>>;
    getTrendingDrawings(limit: bigint): Promise<Array<Drawing>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowingUser(target: UserId): Promise<boolean>;
    likeDrawing(id: DrawingId): Promise<void>;
    listDrawings(offset: bigint, limit: bigint): Promise<Page>;
    listDrawingsByTag(tag: string, offset: bigint, limit: bigint): Promise<Page>;
    postDrawing(input: CreateDrawingInput): Promise<Drawing>;
    saveCallerUserProfile(input: UpdateProfileInput): Promise<void>;
    saveDrawing(id: DrawingId): Promise<void>;
    searchDrawings(searchQuery: string, offset: bigint, limit: bigint): Promise<Page>;
    unfollowUser(target: UserId): Promise<void>;
    unlikeDrawing(id: DrawingId): Promise<void>;
    unsaveDrawing(id: DrawingId): Promise<void>;
    updateDrawing(id: DrawingId, input: UpdateDrawingInput): Promise<void>;
}
import type { CreateDrawingInput as _CreateDrawingInput, Drawing as _Drawing, DrawingId as _DrawingId, ExternalBlob as _ExternalBlob, Page as _Page, Timestamp as _Timestamp, UpdateProfileInput as _UpdateProfileInput, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDrawing(arg0: DrawingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDrawing(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrawing(arg0: DrawingId): Promise<Drawing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrawing(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrawing(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikedBy(arg0: DrawingId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikedBy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikedBy(arg0);
            return result;
        }
    }
    async getSavedDrawings(arg0: bigint, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedDrawings(arg0, arg1);
                return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedDrawings(arg0, arg1);
            return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestedDrawings(arg0: bigint): Promise<Array<Drawing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedDrawings(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedDrawings(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingDrawings(arg0: bigint): Promise<Array<Drawing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingDrawings(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingDrawings(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowingUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowingUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowingUser(arg0);
            return result;
        }
    }
    async likeDrawing(arg0: DrawingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeDrawing(arg0);
            return result;
        }
    }
    async listDrawings(arg0: bigint, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrawings(arg0, arg1);
                return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrawings(arg0, arg1);
            return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDrawingsByTag(arg0: string, arg1: bigint, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrawingsByTag(arg0, arg1, arg2);
                return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrawingsByTag(arg0, arg1, arg2);
            return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async postDrawing(arg0: CreateDrawingInput): Promise<Drawing> {
        if (this.processError) {
            try {
                const result = await this.actor.postDrawing(await to_candid_CreateDrawingInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Drawing_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postDrawing(await to_candid_CreateDrawingInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Drawing_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UpdateProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UpdateProfileInput_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UpdateProfileInput_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDrawing(arg0: DrawingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDrawing(arg0);
            return result;
        }
    }
    async searchDrawings(arg0: string, arg1: bigint, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDrawings(arg0, arg1, arg2);
                return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDrawings(arg0, arg1, arg2);
            return from_candid_Page_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikeDrawing(arg0: DrawingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeDrawing(arg0);
            return result;
        }
    }
    async unsaveDrawing(arg0: DrawingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveDrawing(arg0);
            return result;
        }
    }
    async updateDrawing(arg0: DrawingId, arg1: UpdateDrawingInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrawing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrawing(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_Drawing_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Drawing): Promise<Drawing> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Page_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Promise<Page> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Drawing]): Promise<Drawing | null> {
    return value.length === 0 ? null : await from_candid_Drawing_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    username: string;
    avatarBlob: [] | [_ExternalBlob];
    createdAt: _Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}): Promise<{
    id: UserId;
    bio: string;
    username: string;
    avatarBlob?: ExternalBlob;
    createdAt: Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}> {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        avatarBlob: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarBlob)),
        createdAt: value.createdAt,
        followerCount: value.followerCount,
        followingCount: value.followingCount
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DrawingId;
    title: string;
    likeCount: bigint;
    imageBlob: _ExternalBlob;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    author: _UserId;
    updatedAt: _Timestamp;
    savedCount: bigint;
}): Promise<{
    id: DrawingId;
    title: string;
    likeCount: bigint;
    imageBlob: ExternalBlob;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    author: UserId;
    updatedAt: Timestamp;
    savedCount: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        imageBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.imageBlob),
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt,
        savedCount: value.savedCount
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Drawing>;
}): Promise<{
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Drawing>;
}> {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: await from_candid_vec_n22(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Drawing>): Promise<Array<Drawing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Drawing_n18(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateDrawingInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDrawingInput): Promise<_CreateDrawingInput> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UpdateProfileInput_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): Promise<_UpdateProfileInput> {
    return await to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageBlob: ExternalBlob;
    tags: Array<string>;
    description: string;
}): Promise<{
    title: string;
    imageBlob: _ExternalBlob;
    tags: Array<string>;
    description: string;
}> {
    return {
        title: value.title,
        imageBlob: await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.imageBlob),
        tags: value.tags,
        description: value.description
    };
}
async function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    avatarBlob?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    avatarBlob: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        avatarBlob: value.avatarBlob ? candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.avatarBlob)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
